/*
 * Copyright 2025-2026 Nuvolaris Inc
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * Browser bundle build for the standalone web UI.
 *
 * Separate from esbuild.config.mjs (which builds the Obsidian CJS plugin). This
 * targets the browser: bundles web/main.tsx → dist-web/main.js (IIFE), emits
 * main.css, and copies index.html. The Node server serves dist-web/ at /.
 *
 * It also embeds the built bundle into the server itself by generating
 * server/web-bundle.generated.ts (every dist-web file inlined as base64). The
 * server serves from that embedded map, so the web UI travels with the server
 * code and does not depend on dist-web/ existing at runtime or on the working
 * directory the server chdir()s into.
 *
 * Usage: node esbuild.web.mjs [production]   (default: watch)
 */
import esbuild from "esbuild";
import process from "process";
import { copyFileSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

const prod = process.argv[2] === "production";
const outdir = "dist-web";
const embedFile = "server/web-bundle.generated.ts";

mkdirSync(outdir, { recursive: true });
copyFileSync("web/index.html", `${outdir}/index.html`);

/**
 * Read every file in dist-web/ and write server/web-bundle.generated.ts, a
 * TypeScript module mapping each relative path to its base64 contents. Called
 * after each (re)build so the embedded copy stays in sync with dist-web/.
 */
function writeEmbedModule() {
	const files = readdirSync(outdir, { withFileTypes: true })
		.filter((d) => d.isFile())
		.map((d) => d.name);
	const entries = files
		.map((name) => {
			const b64 = readFileSync(join(outdir, name)).toString("base64");
			return `\t${JSON.stringify(name)}: ${JSON.stringify(b64)},`;
		})
		.join("\n");
	const module =
		`// AUTO-GENERATED by esbuild.web.mjs — do not edit by hand.\n` +
		`// Maps each dist-web/ file name to its base64 contents so the server can\n` +
		`// serve the web UI without dist-web/ present on disk at runtime.\n` +
		`export const WEB_BUNDLE: Record<string, string> = {\n${entries}\n};\n`;
	writeFileSync(embedFile, module);
	console.log(`[web] embedded ${files.length} file(s) → ${embedFile}`);
}

/**
 * Copy index.html and regenerate the embed module on each (re)build so template
 * edits and rebundles show up in watch mode and in the embedded copy.
 */
const copyHtmlPlugin = {
	name: "copy-html",
	setup(build) {
		build.onEnd(() => {
			copyFileSync("web/index.html", `${outdir}/index.html`);
			writeEmbedModule();
		});
	},
};

const options = {
	entryPoints: ["web/main.tsx"],
	bundle: true,
	format: "iife",
	platform: "browser",
	target: "es2020",
	jsx: "automatic",
	loader: { ".css": "css" },
	define: { "process.env.NODE_ENV": prod ? '"production"' : '"development"' },
	outdir,
	entryNames: "main",
	assetNames: "[name]",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	minify: prod,
	plugins: [copyHtmlPlugin],
};

if (prod) {
	await esbuild.build(options);
	process.exit(0);
} else {
	const ctx = await esbuild.context(options);
	await ctx.watch();
	console.log(`[web] watching → ${outdir}/`);
}
