import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { join, isAbsolute } from "node:path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const args = process.argv.slice(2);
const prod = args.includes("production");

/**
 * Optional working directory to change into at start. Passed from the npm
 * script as `--cwd <dir>` (see package.json — modifiable there). When given,
 * the process chdir's into it and the app URL below is printed so the running
 * app is one click away.
 */
function readFlag(name) {
	const i = args.indexOf(name);
	return i >= 0 && i + 1 < args.length ? args[i + 1] : undefined;
}

const cwdFlag = readFlag("--cwd");
if (cwdFlag) {
	const dir = isAbsolute(cwdFlag) ? cwdFlag : join(process.cwd(), cwdFlag);
	try {
		process.chdir(dir);
	} catch (err) {
		console.error(`Cannot change into ${dir}: ${err.message}`);
		process.exit(1);
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
