#!/bin/sh
#
# Install the bundled trustable-acp server as a single self-contained artifact
# plus portable launcher scripts on PATH:
#
#   ~/.local/lib/truacp/truacp.cjs   — the bundled server (web UI embedded)
#   ~/.local/bin/truacp              — launcher: `exec node <bundle> "$@"`
#   ~/.local/bin/trustable-acp       — the same launcher under the long name
#
# The launchers are plain POSIX shell scripts, not compiled binaries: they are
# architecture-independent, readable, and diffable, and they work in any image
# that already has `node` on PATH (which the Trustable image does). An earlier
# revision shipped a platform-specific single-file executable as
# dist-bin/trustable-acp; that is gone — the same path is now a shell script.
#
# Run after `npm run build:web` + `npm run build:server` have produced
# dist-bin/truacp.cjs (`npm run build` does all of this).
#
# NOTE: setup.sh phase 3 performs this same install inline and does NOT call this
# script. That duplication is deliberate: setup.sh must stay self-contained so a
# machine with only setup.sh + pi.version + dist-bin/truacp.cjs can install a
# working truacp (SPEC.md §10b). Keep the launcher format here in sync with
# setup.sh's.
set -eu

BUNDLE="dist-bin/truacp.cjs"
LIB_DIR="$HOME/.local/lib/truacp"
BIN_DIR="$HOME/.local/bin"

if [ ! -f "$BUNDLE" ]; then
	echo "✗ $BUNDLE not found — run 'npm run build' first" >&2
	exit 1
fi

mkdir -p "$LIB_DIR" "$BIN_DIR"
cp "$BUNDLE" "$LIB_DIR/truacp.cjs"

# Emit a launcher script at $1. The bundle path is baked in at install time and
# all args (--port, --dir, --config, …) are forwarded to it.
write_launcher() {
	cat >"$1" <<EOF
#!/bin/sh
# trustable-acp launcher — generated by install-bin.sh. Runs the bundled ACP
# server with whatever node is on PATH.
exec node "$LIB_DIR/truacp.cjs" "\$@"
EOF
	chmod +x "$1"
}

write_launcher "$BIN_DIR/truacp"
write_launcher "$BIN_DIR/trustable-acp"
# Leave a runnable launcher in the build output too, so dist-bin/ is complete.
write_launcher "dist-bin/trustable-acp"

echo "✓ Installed:"
echo "    $LIB_DIR/truacp.cjs"
echo "    $BIN_DIR/truacp"
echo "    $BIN_DIR/trustable-acp"
case ":$PATH:" in
*":$BIN_DIR:"*) ;;
*) echo "⚠ $BIN_DIR is not on PATH — add it to use 'truacp' directly" >&2 ;;
esac
